---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: backing up existing authorized_keys file on {{ inventory_hostname }}
    copy:
      src: .ssh/authorized_keys
      dest: .ssh/authorized_keys.bak
      remote_src: yes
  - name: copying new sshkey to {{ inventory_hostname }}
    authorized_key:
      user: khurram
      state: present
      key: "{{ lookup('file', '.ssh/newtemp/id_rsa.pub') }}"
  - name: confirming new sshkey works on {{ inventory_hostname }}
    local_action: shell ssh -o StrictHostKeyChecking=no -i .ssh/newtemp/id_rsa khurram@{{ inventory_hostname }} 2>/dev/null 2>&1 && echo success || echo failed
    register: connection1_test
    ignore_errors: yes
    failed_when: false
  - name: revert if sshkey confirmation failed on {{ inventory_hostname }}
    local_action: shell ssh -o StrictHostKeyChecking=no -i .ssh/id_rsa khurram@{{ inventory_hostname }} "mv .ssh/authorized_keys.bak .ssh/authorized_keys"
    when: connection1_test.stdout.find('failed') != -1
  - name: removing old sshkey from authorized_keys file
    authorized_key:
      user: khurram
      state: absent
      key: "{{ lookup('file', '/home/khurram/.ssh/id_rsa.pub') }}"
    when: connection1_test.stdout.find('success') != -1
  - name: confirming again if the new sshkey works on {{ inventory_hostname }}
    local_action: shell ssh -o StrictHostKeyChecking=no -i .ssh/newtemp/id_rsa khurram@{{ inventory_hostname }} 2>/dev/null 2>&1 && echo success || echo failed
    register: connection2_test
    ignore_errors: yes
    failed_when: false
  - name: revert if sshkey confirmation failed on {{ inventory_hostname }}
    local_action: shell ssh -o StrictHostKeyChecking=no -i .ssh/id_rsa khurram@{{ inventory_hostname }} "mv .ssh/authorized_keys.bak .ssh/authorized_keys"
    when: connection2_test.stdout.find('failed') != -1
  - name: removing authorized_keys.bak file from {{ inventory_hostname }}
    file:
      path: /home/khurram/.ssh/authorized_keys.bak
      state: absent
    when: connection2_test.stdout.find('success') != -1